include $(TOPDIR)/rules.mk

LUCI_TITLE:=Read-only monitoring for xray-zig
LUCI_DEPENDS:=+luci-base +rpcd-mod-ucode
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0-only

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
